# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) ⚒ Linux AArch build"

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: true

  workflow_call:
    inputs:
      debug:
        type: boolean
        required: true

run-name: Linux AArch64 build${{toJSON(inputs.debug) == 'true' && ' Debug' || ''}}
jobs:
  run-main:
    name: Linux-AArch64
    uses: ./.github/workflows/linux_aarch64_build.yml
    with:
      debug: ${{inputs.debug}}
